- .github/workflows/go-proxy-pull.yaml
- CHANGELOG.md
- Dockerfile
- README.md
> Issue 3.dockter.1

- .github/workflows/go-test.yaml
- CHANGELOG.md
- Dockerfile
- Makefile
- go.mod
- package.Dockerfile
> #7 Update to 1.20

- Makefile
> #11 added the build-scratch target

- .github/workflows/make-go-tag.yaml
> #14 Add make-go-tag.yaml

- Dockerfile
> #16 updated dockerfile

- Makefile
> #19 Fix LD_LIBRARY_PATH

- Dockerfile
- package.Dockerfile
> #30 Added equal sign

- .github/workflows/build-docker-container.yaml
- CHANGELOG.md
- Makefile
- README.md
- docs/README.md
- docs/development.md
- docs/errors.md
- docs/examples.md
- go.mod
- go.sum
> Issue 36.dockter.1

- cmd/root.go
> #40 relocate Version

- cmd/root.go
- go.mod
- go.sum
> #50 Refactor context variables

- .github/workflows/go.yaml
- cmd/github.go
Issue number: Senzing/build resources#27
> Senzing/build resources#27 add gofmt workflow call

- cmd/context_darwin.go
- cmd/context_linux.go
- cmd/context_windows.go
- cmd/root.go
> #57 Support platform-specific context variables

- cmd/context_darwin.go
- cmd/context_linux.go
- cmd/context_windows.go
- cmd/root.go
> #57 Added StringSlices

- .github/workflows/go-test-darwin.yaml
- .github/workflows/go-test-linux.yaml
> #76 Add darwin testing

- .github/workflows/go-test-darwin.yaml
> Updated Darwin workflow to set LD_LIBRARY_PATH and DYLD_LIBRARY_PATH

- Makefile
> #83 Fix make help

- .gitignore
> #76 Minor addition

- Makefile.darwin
> #90 Fix spacing

- .github/workflows/add-dependabot-request-to-project-t-comm.yaml
- .github/workflows/add-issue-to-project-t-comm.yaml
- .github/workflows/add-triage-label.yaml
- .github/workflows/docker-build-container.yaml
- .github/workflows/docker-push-containers-to-dockerhub.yaml
- .github/workflows/go-test-darwin.yaml
- .github/workflows/go-test-linux.yaml
- .github/workflows/go-test-windows.yaml
- .github/workflows/gosec.yaml
- .github/workflows/identify-customer.yaml
- Makefile.darwin
> 90.dockter.3

- .github/workflows/docker-build-container.yaml
- .github/workflows/docker-push-containers-to-dockerhub.yaml
- Dockerfile
- Makefile
- examplepackage/examplepackage_examples_test.go
- examplepackage/examplepackage_test.go
> #92 Move examples to it's own file

- .github/workflows/go-test-darwin.yaml
- .github/workflows/go-test-linux.yaml
- .github/workflows/go-test-windows.yaml
> #101 Fix name

- go.mod
- go.sum
> #104 Update dependencies

- .github/workflows/make-go-github-file.yaml
- Dockerfile
- makefiles/darwin.mk
- makefiles/linux.mk
- makefiles/linux_arm64.mk
- makefiles/linux_x86_64.mk
- makefiles/osdetect.mk
- makefiles/windows.mk
- package.Dockerfile
> #111 Better support for arm64

- .github/workflows/add-to-project-garage-dependabot.yaml
- .github/workflows/add-to-project-garage.yaml
> #118 Use variables

- .github/workflows/add-to-project-garage.yaml
> #122 Use vars instead of env

- .github/workflows/add-labels-standardized.yaml
Issue number: senzing-factory/build-resources#69
> senzing-factory/build-resources#69 typo

- .github/workflows/add-to-project-garage-dependabot.yaml
- .github/workflows/add-to-project-garage.yaml
> cleanup workflows

- .github/workflows/make-go-github-file.yaml
> add pull request write permission

- .github/workflows/add-labels-standardized.yaml
- .github/workflows/add-to-project-garage-dependabot.yaml
- .github/workflows/add-to-project-garage.yaml
- .github/workflows/dependabot-approve-and-merge.yaml
- .github/workflows/docker-build-container.yaml
- .github/workflows/docker-push-containers-to-dockerhub.yaml
- .github/workflows/go-proxy-pull.yaml
- .github/workflows/go-test-darwin.yaml
- .github/workflows/go-test-linux.yaml
- .github/workflows/go-test-windows.yaml
- .github/workflows/gofmt.yaml
- .github/workflows/gosec.yaml
- .github/workflows/lint-workflows.yaml
- .github/workflows/make-go-github-file.yaml
- .github/workflows/make-go-tag.yaml
Issue number: senzing-factory/build-resources#69
> senzing-factory/build-resources#69 add linting

- go.mod
- go.sum
> #143 Update dependencies

- Dockerfile
- Makefile
- docs/development.md
- go.mod
- go.sum
- makefiles/linux.mk
- package.Dockerfile
> 156 dockter 1

- Dockerfile
- package.Dockerfile
> #158 Fix Docker syntax

- Makefile
- docs/development.md
- makefiles/darwin.mk
- makefiles/darwin_arm64.mk
- makefiles/linux.mk
- makefiles/linux_arm64.mk
> #162 Delete System Unit Test (sut) image

- .github/workflows/go-test-darwin.yaml
- .github/workflows/go-test-linux.yaml
- .github/workflows/go-test-windows.yaml
- .github/workflows/golangci-lint.yaml
> update osx and win install 

- .github/workflows/go-test-darwin.yaml
- bin/macos_exec_dyld.sh
- go.mod
- go.sum
> #185 Update dependencies

- .github/workflows/add-labels-standardized.yaml
- .github/workflows/add-to-project-garage-dependabot.yaml
- .github/workflows/add-to-project-garage.yaml
- .github/workflows/docker-push-containers-to-dockerhub.yaml
- .github/workflows/go-proxy-pull.yaml
- .github/workflows/go-test-linux.yaml
- .github/workflows/make-go-github-file.yaml
- .github/workflows/make-go-tag.yaml
Issue number: senzing-factory/build-resources#179
> senzing-factory/build-resources#179 add slack notifications

- .github/workflows/bearer.yaml
> #204 add bearer security checks

- .github/workflows/go-test-darwin.yaml
- .github/workflows/go-test-linux.yaml
- .github/workflows/go-test-windows.yaml
> remove coverage from slack, add cron examples

- .github/workflows/go-test-linux.yaml
> more detail

- .github/workflows/go-test-darwin.yaml
- .github/workflows/go-test-windows.yaml
> fix triggers

- package.Dockerfile
> #216 Bump go version

- .github/workflows/go-test-darwin.yaml
- .github/workflows/golangci-lint.yaml
- .github/workflows/govulncheck.yaml
- package.Dockerfile
> #216 Clean workflows
